import type { Job, JobApplication, CandidateReport } from "./types"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    type: "full-time",
    salary: {
      min: 120000,
      max: 160000,
      currency: "USD",
    },
    description:
      "We are looking for a Senior Frontend Developer to join our dynamic team. You will be responsible for building user-facing features using modern web technologies.",
    requirements: [
      "5+ years of experience in frontend development",
      "Strong proficiency in React and TypeScript",
      "Experience with modern build tools and CI/CD",
      "Bachelor's degree in Computer Science or related field",
    ],
    mustHaveSkills: ["React", "TypeScript", "JavaScript", "HTML/CSS", "Git"],
    goodToHaveSkills: ["Next.js", "GraphQL", "AWS", "Docker", "Jest"],
    postedDate: "2024-01-15",
    applicationDeadline: "2024-02-15",
    status: "active",
    applicantCount: 24,
    recruiterId: "1",
  },
  {
    id: "2",
    title: "Product Manager",
    company: "InnovateLabs",
    location: "New York, NY",
    type: "full-time",
    salary: {
      min: 100000,
      max: 140000,
      currency: "USD",
    },
    description:
      "Join our product team to drive the development of cutting-edge solutions. You'll work closely with engineering, design, and business stakeholders.",
    requirements: [
      "3+ years of product management experience",
      "Strong analytical and problem-solving skills",
      "Experience with agile development methodologies",
      "Excellent communication and leadership skills",
    ],
    mustHaveSkills: ["Product Strategy", "Agile", "Data Analysis", "Stakeholder Management"],
    goodToHaveSkills: ["SQL", "A/B Testing", "User Research", "Figma", "Jira"],
    postedDate: "2024-01-20",
    applicationDeadline: "2024-02-20",
    status: "active",
    applicantCount: 18,
    recruiterId: "1",
  },
  {
    id: "3",
    title: "UX Designer",
    company: "DesignStudio",
    location: "Remote",
    type: "remote",
    salary: {
      min: 80000,
      max: 110000,
      currency: "USD",
    },
    description:
      "We're seeking a talented UX Designer to create intuitive and engaging user experiences for our digital products.",
    requirements: [
      "4+ years of UX design experience",
      "Proficiency in design tools like Figma or Sketch",
      "Strong portfolio demonstrating user-centered design",
      "Experience with user research and testing",
    ],
    mustHaveSkills: ["Figma", "User Research", "Prototyping", "Wireframing", "Design Systems"],
    goodToHaveSkills: ["HTML/CSS", "JavaScript", "After Effects", "Principle", "InVision"],
    postedDate: "2024-01-18",
    applicationDeadline: "2024-02-18",
    status: "active",
    applicantCount: 31,
    recruiterId: "1",
  },
]

export const mockApplications: JobApplication[] = [
  {
    id: "1",
    jobId: "1",
    candidateId: "2",
    candidateName: "John Smith",
    candidateEmail: "candidate@email.com",
    status: "screening",
    appliedDate: "2024-01-22",
    matchScore: 85,
  },
  {
    id: "2",
    jobId: "1",
    candidateId: "3",
    candidateName: "Emily Johnson",
    candidateEmail: "emily.johnson@email.com",
    status: "pending",
    appliedDate: "2024-01-23",
    matchScore: 92,
  },
  {
    id: "3",
    jobId: "2",
    candidateId: "4",
    candidateName: "Michael Brown",
    candidateEmail: "michael.brown@email.com",
    status: "interview",
    appliedDate: "2024-01-21",
    matchScore: 78,
  },
]

export const mockCandidateReports: CandidateReport[] = [
  {
    candidateId: "2",
    jobId: "1",
    overallMatch: 85,
    skillsMatch: 90,
    experienceMatch: 80,
    confidenceScore: 85,
    softSkillsScore: 88,
    matchReasons: [
      "Strong React and TypeScript experience",
      "5+ years of frontend development",
      "Experience with modern build tools",
    ],
    mismatchReasons: ["Limited experience with GraphQL", "No AWS certification mentioned"],
    prescreeningScore: 82,
  },
  {
    candidateId: "3",
    jobId: "1",
    overallMatch: 92,
    skillsMatch: 95,
    experienceMatch: 88,
    confidenceScore: 90,
    softSkillsScore: 94,
    matchReasons: [
      "Exceptional React and TypeScript skills",
      "6+ years of frontend development experience",
      "Strong experience with Next.js and modern frameworks",
      "Excellent problem-solving abilities",
    ],
    mismatchReasons: ["Limited AWS experience", "No Docker experience mentioned"],
    prescreeningScore: 89,
  },
  {
    candidateId: "4",
    jobId: "2",
    overallMatch: 78,
    skillsMatch: 75,
    experienceMatch: 82,
    confidenceScore: 76,
    softSkillsScore: 85,
    matchReasons: ["Strong product management background", "3+ years of relevant experience", "Good analytical skills"],
    mismatchReasons: ["Limited SQL experience", "No A/B testing experience mentioned"],
    prescreeningScore: 74,
  },
]
